name: Java CI with Maven and PostgreSQL

on:
  push:
    branches: [ "*" ]

jobs:
  app_build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: 'SubscriptApp/pom.xml'
      - name: Build with Maven
        run: mvn -B clean package --file SubscriptApp/pom.xml

  db_build:

    runs-on: ubuntu-latest

    needs: app_build  # Ensure that the 'app_build' job is completed before starting the 'db_build' job

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose
      - name: Start PostgreSQL with Docker Compose
        run: |
          cd ./DockerDB/substrack_postgres/
          docker-compose up -d

  tests_run:

    runs-on: ubuntu-latest

    needs: db_build  # Ensure that the 'db_build' job is completed before starting the 'tests_run' job

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: 'SubscriptApp/pom.xml'
      - name: Run Tests with Maven
        run: mvn -B test --file SubscriptApp/pom.xml
